### ISSUE TITLE
Couldn't find package @fractalwagmi/fractal

### ISSUE THREAD

**Issue by viandwi24** [fractalwagmi/react-sdk#107]
**Describe the bug**
error Couldn't find package "@fractalwagmi/fractal@^0.0.319" required by "@fractalwagmi/fractal-ts-lib@^1.0.1" on the "npm" registry.

**To Reproduce**
1. Package install with "npm i @fractalwagmi/react-sdk" or "yarn add @fractalwagmi/react-sdk"
2. See error package not found

**Expected behavior**
install the package successfully

**Screenshots**
<a href="https://ibb.co/K0516cG"><img src="https://i.ibb.co/3rTJ15s/image.png" alt="image" border="0"></a>

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version 107

**Additional context**
-

**Comment by ricebin** [comment]
trying to fix now
thanks!

**Comment by ricebin** [comment]
can you give 1.1.3 a shot?

thanks

**Comment by viandwi24** [comment]
now it's working thanks to that!!
